### ISSUE TITLE
Database

### ISSUE THREAD

**Issue by smith89k** [webdevmatics/Entrust-Notebookapp#1]
Database migrate error 

`[Illuminate\Database\QueryException]
  SQLSTATE[42000]: Syntax error or access violation: 1091 Can't DROP 'notebooks_user_id_foreign'; check that column/key exists (SQL: alter table `notebooks` drop foreign
  key `notebooks_user_id_foreign`)`

`[PDOException]
  SQLSTATE[42000]: Syntax error or access violation: 1091 Can't DROP 'notebooks_user_id_foreign'; check that column/key exists`

**Comment by Hassen307** [comment]
@smithfoto i have same problem, did u have the solution?

**Comment by webdevmatics** [comment]
try removing ```$table->dropForeign('notebooks_user_id_foreign');``` this line from create_notebooks_table migration and migrate.
